--- 
title: "An Introduction to Modular Representation Theory"
author: "Amritanshu Prasad"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "These are lecture notes for the course: An introduction to modular representation theory, taught at the AIS, representation theory, held at CMI in June 2022."
---
# Semisimplicity and the Radical
$\DeclareMathOperator*{\End}{End}$
$\DeclareMathOperator*{\rad}{rad}$

::: {.remark}
The first two chapters of these notes are based largely on @MR1715145.
:::
::: {.exercise}
Determine when the ring $\mathbf{F}_p[x]/(x^n-1)$ is semisimple.
Take $n$ to be any positive integer and $p$ to be a prime number.
Here $\mathbf{F}_p$ denotes a finite field with $p$ elements.
:::

Let $K$ be an algebraically closed field, and let $A$ be a finite dimensional $K$-algebra.

::: {.lemma #simple}
Every simple $A$-module is a quotient of ${}_AA$.
:::
::: {.proof}
Suppose that $M$ is a simple $A$-module.
Pick any $m\in M$ such that $m\neq 0$.
Define $\phi_m:A\to M$ by $\phi_m(a)=am$.
Therefore $\phi_m(A)$ is a non-trivial submodule of $M$.
Since $M$ is simple, $\phi_m$ must be surjective.
Therefore, $M\cong A/\mathrm{ker}\phi_m$.
:::
::: {.corollary}
Every simple module is isomorphic to the quotient of the regular module by a left ideal.
:::
::: {.definition}
A left (right, or two-sided) ideal $N$ of $A$ is said to be *nilpotent* if there exists a positive integer $k$ such that $N^k=0$.
Here $N^k$ denotes the span of products of $k$ elements in $N$.
:::
::: {.lemma #nilker}
Let $M$ be a simple modules, $m\in M$ be a non-zero elements, and let $\phi_m$ be as in the proof of Lemma \@ref(lem:simple).
Then every nilpotent left ideal of $A$ is contained in the kernel of $\phi_m$.
:::
::: {proof}
Suppose that $N$ is a nilpotent left ideal of $A$.
Then for any $n\in N$.
Then $\phi_m(N)=Nm$.
If $\phi_m(N)$ is non-zero, the $Nm=M$.
In other words, there exists $n\in N$ such that $nm=m$.
It follows that $n^km=m$ for all $k\geq 0$.
However, if $k$ is chosen such that $N^k=0$, then $n^k=0$, so $m=n^km=0$, a contradiction.
:::
::: {.lemma #sumnil}
If $N_1$ and $N_2$ are nilpotent left ideals, then $N_1+N_2$ is also a nilpotent left ideal.
:::
::: {proof}
Choose $k$ such that $N_1^k=N_2^k=0$.
An element of $(N_1+N_2)^{2k}$ is a sum of products of $2k$ elements that are drawn either from $N_1$, or from $N_2$.
Such a product will have at least $k$ terms from $N_1$ or at least $k$ terms from $N_2$.
Therefore such a product will lie in $N_1^k$ of $N_2^k$, hence will be $0$.
:::
::: {.exercise}
Let $n_1=\begin{pmatrix}0&1\\0&0\end{pmatrix}$ and $n_2=\begin{pmatrix}0&0\\1&0\end{pmatrix}$.
Then $n_1$ and $n_2$ are nilpotent, but $n_1+n_2$ is not nilpotent.
Does this contradict Lemma \@ref(lem:sumnil)?
:::
::: {.corollary}
The algebra $A$ has a unique maximal nilpotent left ideal.
:::
::: {.proof}
Begin with any nilpotent left ideal $N$ of $A$ (for example, $N=(0)$).
If $N$ is not maximal, then there exists another nilpotent left ideal $N_2$ of $A$ that is not contained in $N_1$.
By Lemma \@ref(lem:sumnil), $N_1+N_2$ is a nilpotent left ideal of $A$ that is strictly larger than $N_1$.
Since $A$ is finite dimensional, this process must terminate in a finite number of steps, thereby giving rise to a maximal nilpotent left ideal of $A$.
If there was more than one maximal nilptent left ideal in $A$, the sum of two such would be a nilpotent ideal strictly larger than either of them, contradicting their maximality.
:::
::: {.definition}
The *radical* of $A$, denoted $\rad(A)$ is the maximal nilpotent left ideal of $A$.
:::
::: {.proposition}
The ideal $\rad(A)$ is a two-sided ideal.
:::
::: {.proof}
Note that $\rad(A)A$ is a two-sided ideal.
Also, if $\rad(A)^k=0$, then
$$
[\rad(A)A]^k = \rad(A)[A\rad(A)]^{k-1}A = \rad(A)^kA = 0.
$$
Therefore $\rad(A)A$ is a nilpotent left ideal containing $\rad(A)$, hence is equal to $\rad(A)$.
:::
::: {.theorem}
$A$ is semisimple if and only if $\rad(A)=0$.
:::
::: {.proof}
Suppose that $A$ is semisimple.
Then, as a left $A$-module,
$$
A = M_1\oplus \dotsb \oplus M_k
$$
for simple $A$-modules $M_1,\dotsc,M_k$.
Suppose that, under this decomposition the identity element of $A$ is written as
\begin{equation}
(\#eq:pou)
1 = \epsilon_1 + \dotsb + \epsilon_k,
\end{equation}
where $\epsilon_i\in M_i$.
By Lemma \@ref(lem:nilker), every nilpotent left ideal of $A$ is contained in $\ker \phi_{\epsilon_i}$.
Therefore every nilpotent left ideal of $A$ is contained in $\ker(\phi_{\epsilon_1}+\dotsb + \phi_{\epsilon_k})$.
But \@ref(eq:pou) implies that
$$
\phi_{\epsilon_1}+\dotsb + \phi_{\epsilon_k} = \phi_1 = \mathrm{id}_A.
$$
If follows that $A$ has no nontrivial nilpotent left ideals, and hence $\rad(A)=0$.

For the converse, suppose that $\rad(A)=0$.
If ${}_AA$ is simple, then $A$ is semisimple.
If not, $A$ has a non-trivial proper left ideal.
Let $N$ be a minimal non-trivial proper left ideal of $A$.
Since $N$ is not nilpotent, $N^2\neq (0)$.
Therefore $N^2=N$.
It follows that there exists $a\in N$ such that $Na\neq 0$.
Again, minimality of $N$ implies that $Na=N$.

Let
$$
B = \{b\in N\mid ba= 0\}.
$$
Then $B$ is a left ideal of $N$.
:::
::: {.exercise}
If $N\subset A$ is a left ideal, $N$ is a submodule of ${}_AA$.
Thus, the vector space $N/A$ inherits the structure of a left $A$-module.
Show that if $N$ is a two-sided ideal, then $N/A$ inherits the structure of a $K$-algebra.
In particular $A/\rad(A)$ is a $K$-algebra.
:::
